[package]
name = "PQC_kyber"
version = "0.1.0"
edition = "2021"

[dependencies]
pqcrypto-kyber = "0.7.9"
pqcrypto-traits = "0.3.5"
anyhow = "1.0"
rand = "0.8.5"
rsa = { version = "0.9.6", features = ["serde", "pem"] }
rand_core = "0.6.4"
criterion = "0.4"
secrecy = "0.8"

chrono = "0.4"
uuid = { version = "1.8", features = ["v4", "serde"] }  # Dodaj feature 'serde'
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
crc32fast = "1.4.2"

[[bench]]
name = "benchmarks"
harness = false