[package]
name = "PQC_kyber"
version = "0.1.0"
edition = "2021"

[dependencies]
pqcrypto-kyber = "0.7.9"
pqcrypto-traits = "0.3.5"
anyhow = "1.0"
rand = "0.8.5"
rsa = { version = "0.9.6", features = ["serde", "pem"] }
rand_core = "0.6.4"
secrecy = "0.8"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full", "rt-multi-thread"] }
indicatif = "0.17.7"
chrono = "0.4"
p256 = { version = "0.13.2", features = ["ecdh"] }


[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "benchmarks"
harness = false


